# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "<YOUR_CLIENT_ID>"
name = "<YOUR_APP_NAME>"
application_url = "<YOUR_APP_URL>"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

# [START access-scopes]
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"
# [END access-scopes]

[auth]
redirect_urls = [ "<YOUR_APP_URL>/api/auth" ]

# [START metaobject-definition]
[metaobjects.app.qrcode]
name = "QR Code"
display_name_field = "title"

  [metaobjects.app.qrcode.access]
  admin = "merchant_read_write"

[metaobjects.app.qrcode.fields.title]
type = "single_line_text_field"
name = "Title"
required = true

[metaobjects.app.qrcode.fields.product]
type = "product_reference"
name = "Product"

[metaobjects.app.qrcode.fields.product_variant]
type = "variant_reference"
name = "Product Variant"

[metaobjects.app.qrcode.fields.destination]
type = "single_line_text_field"
name = "Destination"

  [metaobjects.app.qrcode.fields.destination.validations]
  choices = [ "product", "cart" ]

[metaobjects.app.qrcode.fields.scans]
type = "number_integer"
name = "Scans"
# [END metaobject-definition]
