# This file stores configurations for your Shopify app.
name = "Example App"
client_id = "a61950a2cbd5f32876b0b55587ec7a27"
application_url = "https://www.app.example.com/"
embedded = true
handle = "example-app"

# [START get-access-scopes]
[access_scopes]
scopes = "write_products, read_orders"
# [END get-access-scopes]

# [START change-api-version]
[webhooks]
api_version = "2024-07"
# [END change-api-version]

# [START configure-subscription-pubsub]
[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "pubsub://<PROJECT-ID>:<PUBSUB-TOPIC-ID>"
# [END configure-subscription-pubsub]

# [START configure-subscription-https]
[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/app/orders-create"
# [END configure-subscription-https]

# [START configure-subscription-eventbridge]
[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "arn:aws:events:<AWS-REGION>::event-source/aws.partner/shopify.com/<APP-ID>/<EVENT-SOURCE-NAME>"
# [END configure-subscription-eventbridge]
