# This file stores configurations for your Shopify app.

scopes = "write_products, read_orders"

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "<YOUR-APP-URL>/webhooks"
